import type { Metadata } from "next";
import { Urbanist, Red_Hat_Display, Cousine } from 'next/font/google'
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const urbanist = Urbanist({
  subsets: ['latin'],
  display: 'swap',
  variable: "--font-urbanist",
})

export const redHatDisplay = Red_Hat_Display({
  subsets: ['latin'],
  display: 'swap',
  variable: "--font-redHatDisplay",
})

export const cousine = Cousine({
  subsets: ['latin'],
  display: 'swap',
  variable: "--font-cousine",
  weight: "400",
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${urbanist.variable} ${redHatDisplay.variable} ${cousine.variable}`}>
      <body>
        {children}
      </body>
    </html>
  );
}

